### ISSUE TITLE
Height in iOS 7

### ISSUE THREAD

**Issue by twakebe** [JonasGessner/JGProgressView#1]
The heigtht in iOS7 is not sizeable.

**Comment by JonasGessner** [comment]
Fixed in 76398989fa85118111dd7154cd3a7ededff70e77.

**Comment by Tommecpe** [comment]
Hello,
Thanx for the hard work !
But it seam for me that the height is still not sizable in iOS7. here is my code:

```
    JGProgressView *progressView = [[JGProgressView alloc] initWithFrame:CGRectMake(100, 100, 200, 36)];

progressView.animationSpeed = -1.5;
progressView.animationImage = [UIImage imageNamed:@"Alternative.png"];

[self.view addSubview:progressView];

progressView.indeterminate = YES;
```

And my progress view height is 2 pixels. Do you have an idea why ?

**Comment by JonasGessner** [comment]
Oh I think I misunderstood this issue in the first place (the description wasn't very detailed..). UIProgressView automatically sizes itself to 2 pixels of height, could be tricky to get a workaround.

**Comment by Tommecpe** [comment]
I guess it will be possible to custom the UIProgressView like a regulard progress view ?

**Comment by JonasGessner** [comment]
I'm closing this because this issue is related to UIKit and not directly to JGProgressView.
